<?php
/**
 * partial loop of Partners
 * Partners
 */
 
    $dataRow       = $this->dataRow;
    
?>
<tr>

    <td>
        <?php echo $dataRow->partner_code;?>
    </td>

    <td>
        <?php echo $dataRow->partner_name;?>
    </td>

    <td>
        <?php echo $dataRow->service_code;?>
    </td>

    <td>
        <?php echo $dataRow->contact_name;?>
    </td>

    <td>
        <?php echo $dataRow->contact_email;?>
    </td>

    <td>
        <?php echo $dataRow->contact_phone;?>
    </td>

    <td>
        <?php echo $dataRow->status;?>
    </td>

    <td>
        <?php echo $dataRow->credit;?>
    </td>

    <td>
        <a href="/partners/charge/id/<?php echo $dataRow->id; ?>" class="btn btn-info btn-sm"> 
            
           Charge
        </a>
        <a href="/credit-transaction/show-credit-transaction/fieldsearch/partner_id/keywords/<?php echo $dataRow->id; ?>" class="btn btn-info btn-sm"> 
            Credit Transactions
        </a>
        <a href="/partners/update-partners/id/<?php echo $dataRow->id; ?>" class="btn btn-warning btn-sm">  
           Update
        </a>
    </td>
</tr>