<?php
/**
 * partial loop of Partners
 * Partners
 */
 
    $dataRow       = $this->dataRow;
    
?>
<tr>

    <td>
        <?php echo $dataRow->partner_code;?>
    </td>

    <td>
        <a href="<?php $this->url(array('controller' => 'partners', 'action' => 'detail', 'params' => array('id' =>$dataRow->id )))?>">
            <?php echo $dataRow->partner_name;?>
        </a>
    </td>

    <td>
        <?php echo $dataRow->service_code;?>
    </td>

    <td>
        <?php echo $dataRow->contact_name;?>
    </td>

    <td>
        <?php echo $dataRow->contact_email;?>
    </td>

    <td>
        <?php echo $dataRow->contact_phone;?>
    </td>

    <td>
        <?php echo $dataRow->status;?>
    </td>

    <td>
        <?php echo $dataRow->credit;?>
    </td>

    <td>
        <a href="<?php echo $this->url(array('controller' => 'partners', 'action' => 'charge', 'id' =>$dataRow->id ))?>" class="btn btn-info btn-sm"> 
           Charge
        </a>
        <a href="<?php echo  $this->url(array('controller' => 'credit-transaction', 'action' => 'show-credit-transaction', 'fieldsearch' => 'partner_id' ,'keywords' =>$dataRow->id ))?>" class="btn btn-info btn-sm"> 
            Credit Transactions
        </a>
        
        <a href="<?php echo  $this->url(array('controller' => 'partners', 'action' => 'update-partners','id' =>$dataRow->id ))?>" class="btn btn-warning btn-sm">  
           Update
        </a>
    </td>
</tr>