<div class="row-fluid show-grid form-horizontal">
	<div class="span12">
		<h2>Gen code</h2>
	</div>
</div>
<style>
<!--
.bs-glyphicons li {
	background-color: rgba(86, 61, 124, 0.0980392);
	color: rgb(51, 51, 51);
	display: list-item;
	float: left;
	
	height: 115px;
	line-height: 16px;
	list-style-image: none;
	list-style-position: outside;
	list-style-type: none;
	margin-bottom: -1px;
	margin-left: 0px;
	margin-right: -1px;
	margin-top: 0px;
	padding-bottom: 10px;
	padding-left: 10px;
	padding-right: 10px;
	padding-top: 10px;
	text-align: center;
	width: 105.9375px;
}
-->
</style>
<div class="row">
	<div class="col-md-12">
		<ul class="bs-glyphicons">
			<li><span class="glyphicon glyphicon-adjust"></span> .glyphicon
				.glyphicon-adjust</li>
			<li><span class="glyphicon glyphicon-align-center"></span> .glyphicon
				.glyphicon-align-center</li>
			<li><span class="glyphicon glyphicon-align-justify"></span>
				.glyphicon .glyphicon-align-justify</li>
			<li><span class="glyphicon glyphicon-align-left"></span> .glyphicon
				.glyphicon-align-left</li>
		</ul>
	</div>
</div>
