<div class="row">
    <div class="col-md-12">
        <h2>Payment service administration</h2>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="table-responsive">
            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>Partner Id</th>
                        <th>Partner Code</th>
                        <th>Partner Name</th>
                        <th>Credit Amount</th>
                        <th>Topup Amount</th>
                    </tr>
                </thead>
                <tbody>
                   <?php foreach ($this->records as $record):?>
        
                    <tr>
                        <td><?php echo $record->partner_id?></td>
                        <td><?php echo $record->partner_code?></td>
                        <td><?php echo $record->partner_name?></td>
                        <td style="color: #b55; text-align: right;"><?php echo $record->CreditAmount?$record->CreditAmount:0;?></td>
                        <td style="color: #5b5; text-align: right;"><?php echo $record->TopupAmount?$record->TopupAmount:0?></td>
                    </tr>
                    <?php endforeach;?>
               </tbody>
               
            </table>
        </div>
    </div>
</div>