        <table class="table table-striped table-bordered table-condensed">

            <thead>
                <tr>
                    <th>No.</th>
                    <th>Invoice Id</th>
                    <th>Charged Date</th>
                    <th>Amount</th>
                    <th>Real Revenue</th>
                    <th>Activator</th>
                </tr>
            </thead>

            <tbody>
                <?php if (count($this->paginator) != 0) : ?>
                    <?php 
                        foreach ($this->paginator as $row){
    
                            echo $this->partial('credit-transaction/_partial/ajax-show-credit-transaction.phtml', array('dataRow'=>$row) );
                        }
                    ?>
                <?php else : ?>
                    <tr><td colspan="100"><h3>No Result</h3></td></tr>
                <?php endif; ?>
            </tbody>

            <?php echo $this->renderPaging($this->paginator); ?>
        </table>

        <?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); ?>
    </div>
</div>
