<div class="row-fluid show-grid">
    <div class="span12">
        <h2>
            <?php echo $this->text('GarenaCards') ?>
        </h2>
    </div>
</div>
<?php
$typeSearchs = array(
    'All' => 'All',
    'cardno'                       => $this->text('Cardno', false),
    'value'                        => $this->text('Value', false),
    'days'                         => $this->text('Days', false),
    'uid'                          => $this->text('Uid', false),
    'added_time'                   => $this->text('Added Time', false),
    'status'                       => $this->text('Status', false),
    'extra'                        => $this->text('Extra', false),
    'topup_id'                     => $this->text('Topup Id', false),
);
$buttons = array(
    "<a class='btn btn-success btn-small'  
        href='{$this->url(array('action' => 'add-'. $this->controller))}'>
        <i class='icon-plus'></i>
        Add {$this->text($this->controller)}
    </a>"
);
echo $this->searchBar($typeSearchs, null, $buttons);

?>


<div class="row-fluid show-grid">
    <div class="span12">
        <table class="table table-striped table-bordered table-condensed">

            <thead>
                <tr>
                    <?php $this->renderTh('Cardno'); ?>
                    <?php $this->renderTh('Value'); ?>
                    <?php $this->renderTh('Days'); ?>
                    <?php $this->renderTh('Uid'); ?>
                    <?php $this->renderTh('Added Time'); ?>
                    <?php $this->renderTh('Status'); ?>
                    <?php $this->renderTh('Extra'); ?>
                    <?php $this->renderTh('Topup Id'); ?>
                    
                    <th style='height:42px; line-height:42px; vertical-align:middle;'> Actions</th>
                </tr>
            </thead>

            <tbody>
                <?php if (count($this->paginator) != 0) : ?>
                    <?php 
                        foreach ($this->paginator as $row){
    
                            echo $this->partial('garena-cards/_partial/show-garena-cards.phtml', array('dataRow'=>$row) );
                        }
                    ?>
                <?php else : ?>
                    <tr><td colspan="100"><h3>No Result</h3></td></tr>
                <?php endif; ?>
            </tbody>

            <?php echo $this->renderPaging($this->paginator); ?>
        </table>

        <?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); ?>
    </div>
</div>
