<div class="row show-grid">
    <div class="col-md-12">
        <h2>
            <?php echo $this->text('ServiceLogs') ?>
        </h2>
    </div>
</div>
<?php
$typeSearchs = array(
    'All' => 'All',
    'id'                           => $this->text('id', false),
    'log_type'                     => $this->text('log_type', false),
    'gg_username'                  => $this->text('gg_username', false),
    'partner_id'                   => $this->text('partner_id', false),
    'topup_value'                  => $this->text('topup_value', false),
    'topup_partner_txnid'          => $this->text('topup_partner_txnid', false),
    'extra'                        => $this->text('extra', false),
    'datetime'                     => $this->text('datetime', false),
    'ip_address'                   => $this->text('ip_address', false),
);
$buttons = array(
//     "<a class='btn btn-small'  
//         href='{$this->url(array('action' => 'add-'. $this->controller))}'>
//         <i class='icon-plus'></i>
//         Add {$this->text($this->controller)}
//     </a>"
);
echo $this->searchBar($typeSearchs, null, $buttons);

?>


<div class="row show-grid">
    <div class="col-md-12">
        <table class="table table-striped table-bordered table-condensed">

            <thead>
                <tr>
                    <?php $this->renderTh('log_type'); ?>
                    <?php $this->renderTh('gg_username'); ?>
                    <?php $this->renderTh('partner_id'); ?>
                    <?php $this->renderTh('topup_value'); ?>
                    <?php $this->renderTh('topup_partner_txnid'); ?>
                    <?php $this->renderTh('extra'); ?>
                    <?php $this->renderTh('datetime'); ?>
                    <?php $this->renderTh('ip_address'); ?>
                    
                </tr>
            </thead>

            <tbody>
                <?php if (count($this->paginator) != 0) : ?>
                    <?php 
                        foreach ($this->paginator as $row){
    
                            echo $this->partial('service-logs/_partial/show-service-logs.phtml', array('dataRow'=>$row) );
                        }
                    ?>
                <?php else : ?>
                    <tr><td colspan="100"><h3>No Result</h3></td></tr>
                <?php endif; ?>
            </tbody>

            <?php echo $this->renderPaging($this->paginator); ?>
        </table>

        <?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); ?>
    </div>
</div>
