<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<!-- add title for page at here -->
<title>Admin Control Panel</title>

<!--<script src="<?php echo STATIC_SERVER;?>/scripts/jquery.js" type="text/javascript"></script>-->
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/jquery-ui.min.js"></script>

<link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.21/themes/base/jquery-ui.css" type="text/css" media="all" />

<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet">
<link href="<?php echo STATIC_SERVER;?>/styles/main.css" rel="stylesheet" type="text/css" />
    
<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
<script src="<?php echo STATIC_SERVER;?>/scripts/scripts.js" type="text/javascript"></script>

</head>
<body>

  <?php echo $this->render("header.phtml"); ?>

  <?php  echo $this->layout()->content ?>
  <?php  echo $this->render("footer.phtml"); ?>


</body>
</html>
