<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<!-- add title for page at here -->
<title>Admin Control Panel</title>
<?php 


$this->headScript()->appendFile('https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js', 'text/javascript');

// $this->headLink()->appendStylesheet('http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.21/themes/base/jquery-ui.css');

$this->headScript()->appendFile('https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/jquery-ui.min.js', 'text/javascript');

$this->headLink()->appendStylesheet('http://netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css');
$this->headScript()->appendFile('http://netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js', 'text/javascript');


$this->headLink()->appendStylesheet($this->baseUrl('styles/main.css'));


$this->headScript()->appendFile($this->baseUrl('scripts/scripts.js', 'text/javascript'));

?>
<?php echo $this->headScript()?>
<?php echo $this->headLink() ?>

</head>
<body>

  <?php echo $this->render("header.phtml"); ?>

  <?php  echo $this->layout()->content ?>
  <?php  echo $this->render("footer.phtml"); ?>



</body>
</html>
