<?php
/**
 * partial loop of GarenaCards
 * GarenaCards
 */
$dataRow = $this->dataRow;

?>
<tr>

	<td>
        <?php echo $dataRow->cardno;?>
    </td>

	<td>
        <?php echo $dataRow->value;?>
    </td>

	<td>
        <?php echo $dataRow->days;?>
    </td>

	<td>
        <?php echo $dataRow->uid;?>
    </td>

	<td>
        <?php echo $dataRow->added_time;?>
    </td>

	<td>
        <?php echo $dataRow->status;?>
    </td>

	<td>
        <?php echo $dataRow->extra;?>
    </td>

	<td>
        <?php echo $dataRow->topup_id;?>
    </td>

	<td><a
		href="<?php echo $this->url(array(
		    'controller' => 'garena-cards', 
		    'action' => 'update-garena-cards', 
		    'id' =>$dataRow->id ))?>"
		class="btn btn-warning btn-sm"> <i class="icon-edit"></i> Update
	</a> <a
		href="<?php echo  $this->url(array(
		    'controller' => 'garena-cards',
		    'action' => 'delete-garena-cards', 
		    'id' =>$dataRow->id ))?>"
		class="btn btn-danger btn-sm " onclick="return confirm('Are you sure?');"> <i class="icon-remove icon-white"></i>
			Delete
	</a></td>
</tr>