<?php 
    $form = $this->form;
?>
<div class="row">
  <div class="col-md-12">
          <div class="pull-right">
              <a href="<?php echo $this->url(array('controller'=>'partners', 'action'=>'show-partners'), null, true) ?>" >
                  Back to list <?php echo $this->text('Partners'); ?>
              </a>
          </div>
          <h2>
              Charge <?php echo $this->text('From Partner - Credit Transaction'); ?>        
          </h2>
    </div>
</div>

<?php if(isset($this->isSaved)): ?>
<div class="row">
  <div class="col-md-12">
        <?php if($this->isSaved):?>
            <div class="alert alert-success">
                <?php echo $this->text('CreditTransaction'); ?> saved succcessfully!
            </div>
        <?php else: ?>
            <div class="alert alert-danger">
                <?php echo $this->text('CreditTransaction'); ?> saved fail!
            </div>
        <?php endif; ?>
    </div>
</div>
<?php endif; ?>

<div class="row">
  <div class="col-md-12">
    <form class="form-horizontal" role="form" method="post" action="">
                
                <?php echo $this->renderFormElement($form->id);?>
                <?php echo $this->renderFormElement($form->partner_id);?>
                <?php echo $this->renderFormElement($form->invoice_id);?>
                <?php echo $this->renderFormElement($form->amount);?>
                <?php echo $this->renderFormElement($form->real_revenue);?>
                <?php echo $this->renderFormElement($form->txn_datetime);?>
                
                <div class="form-group ">
				<label for="topup_id" class="col-lg-2 control-label">&nbsp</label>
				<div class="col-lg-6">
					<button type="submit" class="btn btn-primary">
						<i class="icon-ok icon-white"></i> Submit
					</button>
					<button type="reset" class="btn">
						<i class="icon-refresh"></i> Reset
					</button>
				</div>
		    </div>
        </form>
    </div>
</div>

<script src="<?php echo STATIC_SERVER;?>/scripts/date-time-picker-addon.js" type="text/javascript"></script>
<link href="<?php echo STATIC_SERVER;?>/styles/date-time-picker-addon.css" rel="stylesheet" type="text/css" />
<script>
$(function() {
    $( "#txn_datetime" ).datetimepicker({
    	dateFormat: "yy/mm/dd",
    	altTimeFormat: "h:m t",
    	defaultValue: "<?php echo $this->now;?>"
    });
  });
</script>