<div class="row show-grid">
    <div class="col-md-12">
        <h2>
            <?php echo $this->text('Partners') ?>
        </h2>
    </div>
</div>
<?php
$typeSearchs = array(
    'All' => 'All',
    'id'                           => $this->text('id', false),
    'partner_code'                 => $this->text('Partner_Code', false),
    'partner_name'                 => $this->text('Partner_Name', false),
    'service_code'                 => $this->text('Service_Code', false),
    'contact_name'                 => $this->text('Contact_Name', false),
    'contact_email'                => $this->text('Contact_Email', false),
    'contact_phone'                => $this->text('Contact_Phone', false),
    'status'                       => $this->text('Visible', false),
    'credit'                       => $this->text('Credit', false),
    'created_date'                 => $this->text('Created_Date', false),
    'created_by'                   => $this->text('Created_By', false),
    'ip_address'                   => $this->text('Ip_Address', false),
);
$buttons = array(
    "<a class='btn btn-success btn-small'  
        href='{$this->url(array('action' => 'add-'. $this->controller))}'>
        <i class='icon-plus'></i>
        Add {$this->text($this->controller)}
    </a>"
);
echo $this->searchBar($typeSearchs, null, $buttons);

?>


<div class="row show-grid">
    <div class="col-md-12">
        <table class="table table-striped table-bordered table-condensed">

            <thead>
                <tr>
                    <?php $this->renderTh('Partner Code'); ?>
                    <?php $this->renderTh('Partner Name'); ?>
                    <?php $this->renderTh('Service Code'); ?>
                    <?php $this->renderTh('Contact Name'); ?>
                    <?php $this->renderTh('Contact Email'); ?>
                    <?php $this->renderTh('Contact Phone'); ?>
                    <?php $this->renderTh('Visible'); ?>
                    <?php $this->renderTh('Credit'); ?>
                    
                    <th width="280" style='height:42px; line-height:42px; vertical-align:middle;'>Actions</th>
                </tr>
            </thead>

            <tbody>
                <?php if (count($this->paginator) != 0) : ?>
                    <?php 
                        foreach ($this->paginator as $row){
    
                            echo $this->partial('partners/_partial/show-partners.phtml', array('dataRow'=>$row) );
                        }
                    ?>
                <?php else : ?>
                    <tr><td colspan="100"><h3>No Result</h3></td></tr>
                <?php endif; ?>
            </tbody>

            <?php echo $this->renderPaging($this->paginator); ?>
        </table>

        <?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); ?>
    </div>
</div>
